-- AlterTable
ALTER TABLE "CVE" ADD COLUMN     "containers_adp" JSONB[] DEFAULT ARRAY[]::JSONB[],
ADD COLUMN     "containers_cna_affected" JSONB[] DEFAULT ARRAY[]::JSONB[],
ADD COLUMN     "containers_cna_configurations" JSONB[] DEFAULT ARRAY[]::JSONB[],
ADD COLUMN     "containers_cna_credits" JSONB[] DEFAULT ARRAY[]::JSONB[],
ADD COLUMN     "containers_cna_dateAssigned" TIMESTAMP(3),
ADD COLUMN     "containers_cna_datePublic" TIMESTAMP(3),
ADD COLUMN     "containers_cna_descriptions" JSONB[] DEFAULT ARRAY[]::JSONB[],
ADD COLUMN     "containers_cna_exploits" JSONB[] DEFAULT ARRAY[]::JSONB[],
ADD COLUMN     "containers_cna_impacts" JSONB[] DEFAULT ARRAY[]::JSONB[],
ADD COLUMN     "containers_cna_metrics" JSONB[] DEFAULT ARRAY[]::JSONB[],
ADD COLUMN     "containers_cna_problemTypes" JSONB[] DEFAULT ARRAY[]::JSONB[],
ADD COLUMN     "containers_cna_providerMetadata_dateUpdated" TIMESTAMP(3),
ADD COLUMN     "containers_cna_providerMetadata_orgId" TEXT NOT NULL DEFAULT 'UNSET',
ADD COLUMN     "containers_cna_providerMetadata_shortName" TEXT,
ADD COLUMN     "containers_cna_references" JSONB[] DEFAULT ARRAY[]::JSONB[],
ADD COLUMN     "containers_cna_rejectedReasons" JSONB[] DEFAULT ARRAY[]::JSONB[],
ADD COLUMN     "containers_cna_replacedBy" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "containers_cna_solutions" JSONB[] DEFAULT ARRAY[]::JSONB[],
ADD COLUMN     "containers_cna_source" JSONB,
ADD COLUMN     "containers_cna_tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "containers_cna_taxonomyMappings" JSONB[] DEFAULT ARRAY[]::JSONB[],
ADD COLUMN     "containers_cna_timeline" JSONB[] DEFAULT ARRAY[]::JSONB[],
ADD COLUMN     "containers_cna_title" TEXT,
ADD COLUMN     "containers_cna_workarounds" JSONB[] DEFAULT ARRAY[]::JSONB[],
ADD COLUMN     "cveMetadata_assignerOrgId" TEXT,
ADD COLUMN     "cveMetadata_assignerShortName" TEXT,
ADD COLUMN     "cveMetadata_cveId" TEXT NOT NULL DEFAULT 'UNSET',
ADD COLUMN     "cveMetadata_datePublished" TIMESTAMP(3),
ADD COLUMN     "cveMetadata_dateRejected" TIMESTAMP(3),
ADD COLUMN     "cveMetadata_dateReserved" TIMESTAMP(3),
ADD COLUMN     "cveMetadata_dateUpdated" TIMESTAMP(3),
ADD COLUMN     "cveMetadata_requesterUserId" TEXT,
ADD COLUMN     "cveMetadata_serial" INTEGER,
ADD COLUMN     "cveMetadata_state" TEXT NOT NULL DEFAULT 'UNSET',
ADD COLUMN     "dataType" TEXT NOT NULL DEFAULT 'UNSET',
ADD COLUMN     "dataVersion" TEXT NOT NULL DEFAULT 'UNSET';
