import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1>cve.248.no</h1>
          <div>
            <h3>Examples</h3>
            <p>
              <Link className={styles.link} href="/cve?id=CVE-2021-30900">
                CVE-2021-30900
              </Link>
            </p>
            <p>
              <Link className={styles.link} href="/cve?id=CVE-2021-40444">
                CVE-2021-40444
              </Link>
            </p>
            <p>
              <Link className={styles.link} href="/cve?id=CVE-2022-41099">
                CVE-2022-41099
              </Link>
            </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
