name: Push Container
on:
  push:
    branches:
      - main
      - rosvik/deploy
jobs:
  push-container:
    name: Push Container
    uses: rosvik/workflows/.github/workflows/push-container.yml@main
    with:
      image: rosvik/cve.li
      registry_url: ghcr.io
      registry_username: rosvik
    secrets:
      registry_password: ${{ secrets.GHCR_TOKEN }}
  cubbyman-reload:
    name: Cubbyman Reload
    needs: push-container
    uses: rosvik/workflows/.github/workflows/cubbyman-reload.yml@main
    with:
      base_url: https://cubby.no
    secrets:
      credentials: ${{ secrets.CUBBYMAN_CREDENTIALS }}
